import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/section/Header'
import { getPage } from '@/lib/getPage'
import HeroSection from "./components/section/HeroSection";
import ClientLogosSection from "./components/section/ClientLogosSection";
import SatisfactionSection from "./components/section/SatisfactionSection";
import KPIVsTimeSection from "./components/section/KPIVsTimeSection";
import PlaylistSection from "./components/section/PlaylistSection";
import PriorityTableSection from "./components/section/PriorityTableSection";
import MarketingOpportunitiesSection from "./components/section/MarketingOpportunitiesSection";
import MarketingPlanSection from "./components/section/MarketingPlanSection";
import TeamSection from "./components/section/TeamSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageData = await getPage()
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header data={pageData.header}/>
        <HeroSection data={pageData.hero} />
        <ClientLogosSection data={pageData.clientLogos} />
        <SatisfactionSection data={pageData.satisfaction} />
        <KPIVsTimeSection data={pageData.kpivstime} />
        <PlaylistSection data={pageData.playlistSection} />
        <PriorityTableSection data={pageData.priorityTable} />
        <MarketingOpportunitiesSection data={pageData.marketingOpportunities} />
        <MarketingPlanSection data={pageData.marketingPlan} />
        <TeamSection data={pageData.team}/>
        {children}
      </body>
    </html>
  );
}
